package com.teide.dam.planfinder.pojos;
// Generated Jan 30, 2014 1:02:01 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Grupo generated by hbm2java
 */
@Entity
@Table(name="grupo"
    ,catalog="proyecto"
)
public class Grupo  implements java.io.Serializable {


     private Integer idGrupo;
     private Ubicacion ubicacion;
     private Usuario usuario;
     private Tipo tipo;
     private String nombre;
     private String descripcion;
     private Date fechaCreacion;
     private Date fechaFinalizacion;
     private Date fechaInicioActividad;
     private Date fechaFinActividad;
     private String estado;
     private int radioEmision;
     private Set<Pertenece> perteneces = new HashSet<Pertenece>(0);
     private Set<Mensaje> mensajes = new HashSet<Mensaje>(0);

    public Grupo() {
    }

	
    public Grupo(Usuario usuario, Tipo tipo, String nombre, Date fechaCreacion, String estado, int radioEmision) {
        this.usuario = usuario;
        this.tipo = tipo;
        this.nombre = nombre;
        this.fechaCreacion = fechaCreacion;
        this.estado = estado;
        this.radioEmision = radioEmision;
    }
    public Grupo(Ubicacion ubicacion, Usuario usuario, Tipo tipo, String nombre, String descripcion, Date fechaCreacion, Date fechaFinalizacion, Date fechaInicioActividad, Date fechaFinActividad, String estado, int radioEmision, Set<Pertenece> perteneces, Set<Mensaje> mensajes) {
       this.ubicacion = ubicacion;
       this.usuario = usuario;
       this.tipo = tipo;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.fechaCreacion = fechaCreacion;
       this.fechaFinalizacion = fechaFinalizacion;
       this.fechaInicioActividad = fechaInicioActividad;
       this.fechaFinActividad = fechaFinActividad;
       this.estado = estado;
       this.radioEmision = radioEmision;
       this.perteneces = perteneces;
       this.mensajes = mensajes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idGrupo", unique=true, nullable=false)
    public Integer getIdGrupo() {
        return this.idGrupo;
    }
    
    public void setIdGrupo(Integer idGrupo) {
        this.idGrupo = idGrupo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ubicacion_idubicacion")
    public Ubicacion getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(Ubicacion ubicacion) {
        this.ubicacion = ubicacion;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="creador", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tipo_idTipo", nullable=false)
    public Tipo getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Tipo tipo) {
        this.tipo = tipo;
    }
    
    @Column(name="nombre", nullable=false, length=100)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="descripcion", length=300)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaCreacion", nullable=false, length=19)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaFinalizacion", length=19)
    public Date getFechaFinalizacion() {
        return this.fechaFinalizacion;
    }
    
    public void setFechaFinalizacion(Date fechaFinalizacion) {
        this.fechaFinalizacion = fechaFinalizacion;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaInicioActividad", length=19)
    public Date getFechaInicioActividad() {
        return this.fechaInicioActividad;
    }
    
    public void setFechaInicioActividad(Date fechaInicioActividad) {
        this.fechaInicioActividad = fechaInicioActividad;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaFinActividad", length=19)
    public Date getFechaFinActividad() {
        return this.fechaFinActividad;
    }
    
    public void setFechaFinActividad(Date fechaFinActividad) {
        this.fechaFinActividad = fechaFinActividad;
    }
    
    @Column(name="estado", nullable=false, length=45)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    
    @Column(name="radioEmision", nullable=false)
    public int getRadioEmision() {
        return this.radioEmision;
    }
    
    public void setRadioEmision(int radioEmision) {
        this.radioEmision = radioEmision;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="grupo")
    public Set<Pertenece> getPerteneces() {
        return this.perteneces;
    }
    
    public void setPerteneces(Set<Pertenece> perteneces) {
        this.perteneces = perteneces;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="grupo")
    public Set<Mensaje> getMensajes() {
        return this.mensajes;
    }
    
    public void setMensajes(Set<Mensaje> mensajes) {
        this.mensajes = mensajes;
    }




}


