package com.teide.dam.planfinder.pojos;
// Generated Feb 4, 2014 9:20:18 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PerteneceId generated by hbm2java
 */
@Embeddable
public class PerteneceId  implements java.io.Serializable {


     private String usuarioSim;
     private int grupoIdGrupo;

    public PerteneceId() {
    }

    public PerteneceId(String usuarioSim, int grupoIdGrupo) {
       this.usuarioSim = usuarioSim;
       this.grupoIdGrupo = grupoIdGrupo;
    }
   

    @Column(name="usuario_sim", nullable=false, length=20)
    public String getUsuarioSim() {
        return this.usuarioSim;
    }
    
    public void setUsuarioSim(String usuarioSim) {
        this.usuarioSim = usuarioSim;
    }

    @Column(name="grupo_id_grupo", nullable=false)
    public int getGrupoIdGrupo() {
        return this.grupoIdGrupo;
    }
    
    public void setGrupoIdGrupo(int grupoIdGrupo) {
        this.grupoIdGrupo = grupoIdGrupo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PerteneceId) ) return false;
		 PerteneceId castOther = ( PerteneceId ) other; 
         
		 return ( (this.getUsuarioSim()==castOther.getUsuarioSim()) || ( this.getUsuarioSim()!=null && castOther.getUsuarioSim()!=null && this.getUsuarioSim().equals(castOther.getUsuarioSim()) ) )
 && (this.getGrupoIdGrupo()==castOther.getGrupoIdGrupo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUsuarioSim() == null ? 0 : this.getUsuarioSim().hashCode() );
         result = 37 * result + this.getGrupoIdGrupo();
         return result;
   }   


}


