package com.teide.dam.planfinder.pojos;
// Generated Feb 7, 2014 12:10:03 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Pertenece generated by hbm2java
 */
@Entity
@Table(name="pertenece"
    ,catalog="proyecto"
)
public class Pertenece  implements java.io.Serializable {


     private PerteneceId id;
     private Grupo grupo;
     private Usuario usuario;
     private String estado;

    public Pertenece() {
    }

    public Pertenece(PerteneceId id, Grupo grupo, Usuario usuario, String estado) {
       this.id = id;
       this.grupo = grupo;
       this.usuario = usuario;
       this.estado = estado;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="usuarioSim", column=@Column(name="usuario_sim", nullable=false, length=20) ), 
        @AttributeOverride(name="grupoIdGrupo", column=@Column(name="grupo_id_grupo", nullable=false) ) } )
    public PerteneceId getId() {
        return this.id;
    }
    
    public void setId(PerteneceId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="grupo_id_grupo", nullable=false, insertable=false, updatable=false)
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario_sim", nullable=false, insertable=false, updatable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    
    @Column(name="estado", nullable=false, length=45)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


